// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// CreateFeedsReader is a Reader for the CreateFeeds structure.
type CreateFeedsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFeedsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateFeedsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateFeedsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateFeedsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateFeedsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateFeedsOK creates a CreateFeedsOK with default headers values
func NewCreateFeedsOK() *CreateFeedsOK {
	return &CreateFeedsOK{}
}

/*
CreateFeedsOK describes a response with status code 200, with default header values.

OK
*/
type CreateFeedsOK struct {
	Payload *models.CreateFeedsResponse
}

// IsSuccess returns true when this create feeds o k response has a 2xx status code
func (o *CreateFeedsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create feeds o k response has a 3xx status code
func (o *CreateFeedsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create feeds o k response has a 4xx status code
func (o *CreateFeedsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create feeds o k response has a 5xx status code
func (o *CreateFeedsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create feeds o k response a status code equal to that given
func (o *CreateFeedsOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateFeedsOK) Error() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsOK  %+v", 200, o.Payload)
}

func (o *CreateFeedsOK) String() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsOK  %+v", 200, o.Payload)
}

func (o *CreateFeedsOK) GetPayload() *models.CreateFeedsResponse {
	return o.Payload
}

func (o *CreateFeedsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateFeedsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFeedsBadRequest creates a CreateFeedsBadRequest with default headers values
func NewCreateFeedsBadRequest() *CreateFeedsBadRequest {
	return &CreateFeedsBadRequest{}
}

/*
CreateFeedsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateFeedsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create feeds bad request response has a 2xx status code
func (o *CreateFeedsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create feeds bad request response has a 3xx status code
func (o *CreateFeedsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create feeds bad request response has a 4xx status code
func (o *CreateFeedsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create feeds bad request response has a 5xx status code
func (o *CreateFeedsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create feeds bad request response a status code equal to that given
func (o *CreateFeedsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateFeedsBadRequest) Error() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateFeedsBadRequest) String() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateFeedsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateFeedsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFeedsUnauthorized creates a CreateFeedsUnauthorized with default headers values
func NewCreateFeedsUnauthorized() *CreateFeedsUnauthorized {
	return &CreateFeedsUnauthorized{}
}

/*
CreateFeedsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateFeedsUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create feeds unauthorized response has a 2xx status code
func (o *CreateFeedsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create feeds unauthorized response has a 3xx status code
func (o *CreateFeedsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create feeds unauthorized response has a 4xx status code
func (o *CreateFeedsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create feeds unauthorized response has a 5xx status code
func (o *CreateFeedsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create feeds unauthorized response a status code equal to that given
func (o *CreateFeedsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateFeedsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateFeedsUnauthorized) String() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateFeedsUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateFeedsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFeedsInternalServerError creates a CreateFeedsInternalServerError with default headers values
func NewCreateFeedsInternalServerError() *CreateFeedsInternalServerError {
	return &CreateFeedsInternalServerError{}
}

/*
CreateFeedsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateFeedsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create feeds internal server error response has a 2xx status code
func (o *CreateFeedsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create feeds internal server error response has a 3xx status code
func (o *CreateFeedsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create feeds internal server error response has a 4xx status code
func (o *CreateFeedsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create feeds internal server error response has a 5xx status code
func (o *CreateFeedsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create feeds internal server error response a status code equal to that given
func (o *CreateFeedsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateFeedsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateFeedsInternalServerError) String() string {
	return fmt.Sprintf("[POST /feeds/create][%d] createFeedsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateFeedsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateFeedsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
