// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the feeds client
type API interface {
	/*
	   CreateFeeds creates new feeds*/
	CreateFeeds(ctx context.Context, params *CreateFeedsParams) (*CreateFeedsOK, error)
	/*
	   GetFeeds gets feeds matching the given parameters*/
	GetFeeds(ctx context.Context, params *GetFeedsParams) (*GetFeedsOK, error)
}

// New creates a new feeds API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for feeds API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
CreateFeeds creates new feeds
*/
func (a *Client) CreateFeeds(ctx context.Context, params *CreateFeedsParams) (*CreateFeedsOK, error) {
	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateFeeds",
		Method:             "POST",
		PathPattern:        "/feeds/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateFeedsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateFeedsOK), nil
}

/*
GetFeeds gets feeds matching the given parameters
*/
func (a *Client) GetFeeds(ctx context.Context, params *GetFeedsParams) (*GetFeedsOK, error) {
	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetFeeds",
		Method:             "POST",
		PathPattern:        "/feeds/get",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetFeedsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetFeedsOK), nil
}
