// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new feeds API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for feeds API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateFeeds(params *CreateFeedsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFeedsOK, error)

	GetFeeds(params *GetFeedsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFeedsOK, error)

	GetRss(params *GetRssParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRssOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateFeeds creates new feeds
*/
func (a *Client) CreateFeeds(params *CreateFeedsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFeedsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateFeedsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateFeeds",
		Method:             "POST",
		PathPattern:        "/feeds/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateFeedsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateFeedsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateFeeds: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetFeeds gets feeds matching the given parameters
*/
func (a *Client) GetFeeds(params *GetFeedsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFeedsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFeedsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFeeds",
		Method:             "POST",
		PathPattern:        "/feeds/get",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetFeedsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetFeedsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFeeds: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetRss returns a response with the XML feed in XML format
*/
func (a *Client) GetRss(params *GetRssParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRssOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRssParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetRss",
		Method:             "GET",
		PathPattern:        "/feeds/rss/{id}",
		ProducesMediaTypes: []string{"text/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetRssReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRssOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRss: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
