// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sfs/api/models"
)

// GetFeedsReader is a Reader for the GetFeeds structure.
type GetFeedsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFeedsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFeedsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetFeedsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetFeedsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFeedsOK creates a GetFeedsOK with default headers values
func NewGetFeedsOK() *GetFeedsOK {
	return &GetFeedsOK{}
}

/*
GetFeedsOK describes a response with status code 200, with default header values.

OK
*/
type GetFeedsOK struct {
	Payload *models.GetFeedsResponse
}

// IsSuccess returns true when this get feeds o k response has a 2xx status code
func (o *GetFeedsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get feeds o k response has a 3xx status code
func (o *GetFeedsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get feeds o k response has a 4xx status code
func (o *GetFeedsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get feeds o k response has a 5xx status code
func (o *GetFeedsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get feeds o k response a status code equal to that given
func (o *GetFeedsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetFeedsOK) Error() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsOK  %+v", 200, o.Payload)
}

func (o *GetFeedsOK) String() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsOK  %+v", 200, o.Payload)
}

func (o *GetFeedsOK) GetPayload() *models.GetFeedsResponse {
	return o.Payload
}

func (o *GetFeedsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetFeedsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFeedsUnauthorized creates a GetFeedsUnauthorized with default headers values
func NewGetFeedsUnauthorized() *GetFeedsUnauthorized {
	return &GetFeedsUnauthorized{}
}

/*
GetFeedsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetFeedsUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get feeds unauthorized response has a 2xx status code
func (o *GetFeedsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get feeds unauthorized response has a 3xx status code
func (o *GetFeedsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get feeds unauthorized response has a 4xx status code
func (o *GetFeedsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get feeds unauthorized response has a 5xx status code
func (o *GetFeedsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get feeds unauthorized response a status code equal to that given
func (o *GetFeedsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetFeedsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetFeedsUnauthorized) String() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetFeedsUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFeedsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFeedsInternalServerError creates a GetFeedsInternalServerError with default headers values
func NewGetFeedsInternalServerError() *GetFeedsInternalServerError {
	return &GetFeedsInternalServerError{}
}

/*
GetFeedsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetFeedsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get feeds internal server error response has a 2xx status code
func (o *GetFeedsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get feeds internal server error response has a 3xx status code
func (o *GetFeedsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get feeds internal server error response has a 4xx status code
func (o *GetFeedsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get feeds internal server error response has a 5xx status code
func (o *GetFeedsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get feeds internal server error response a status code equal to that given
func (o *GetFeedsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetFeedsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFeedsInternalServerError) String() string {
	return fmt.Sprintf("[POST /feeds/get][%d] getFeedsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFeedsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFeedsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
