// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRssParams creates a new GetRssParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRssParams() *GetRssParams {
	return &GetRssParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRssParamsWithTimeout creates a new GetRssParams object
// with the ability to set a timeout on a request.
func NewGetRssParamsWithTimeout(timeout time.Duration) *GetRssParams {
	return &GetRssParams{
		timeout: timeout,
	}
}

// NewGetRssParamsWithContext creates a new GetRssParams object
// with the ability to set a context for a request.
func NewGetRssParamsWithContext(ctx context.Context) *GetRssParams {
	return &GetRssParams{
		Context: ctx,
	}
}

// NewGetRssParamsWithHTTPClient creates a new GetRssParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRssParamsWithHTTPClient(client *http.Client) *GetRssParams {
	return &GetRssParams{
		HTTPClient: client,
	}
}

/*
GetRssParams contains all the parameters to send to the API endpoint

	for the get rss operation.

	Typically these are written to a http.Request.
*/
type GetRssParams struct {
	/* ID.

	   Feed ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rss params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRssParams) WithDefaults() *GetRssParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rss params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRssParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rss params
func (o *GetRssParams) WithTimeout(timeout time.Duration) *GetRssParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rss params
func (o *GetRssParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rss params
func (o *GetRssParams) WithContext(ctx context.Context) *GetRssParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rss params
func (o *GetRssParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rss params
func (o *GetRssParams) WithHTTPClient(client *http.Client) *GetRssParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rss params
func (o *GetRssParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get rss params
func (o *GetRssParams) WithID(id string) *GetRssParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get rss params
func (o *GetRssParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRssParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
