repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [ --fix=lf ]

  - repo: https://github.com/mkuznets/pre-commit-hooks
    rev: v0.0.5
    hooks:
      - id: go-mod-tidy
      - id: format-go
        args: [ "-l", "mkuznets.com/go/sfs" ]
