// Code generated by go-swagger; DO NOT EDIT.

package episodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// NewCreateEpisodeParams creates a new CreateEpisodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEpisodeParams() *CreateEpisodeParams {
	return &CreateEpisodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEpisodeParamsWithTimeout creates a new CreateEpisodeParams object
// with the ability to set a timeout on a request.
func NewCreateEpisodeParamsWithTimeout(timeout time.Duration) *CreateEpisodeParams {
	return &CreateEpisodeParams{
		timeout: timeout,
	}
}

// NewCreateEpisodeParamsWithContext creates a new CreateEpisodeParams object
// with the ability to set a context for a request.
func NewCreateEpisodeParamsWithContext(ctx context.Context) *CreateEpisodeParams {
	return &CreateEpisodeParams{
		Context: ctx,
	}
}

// NewCreateEpisodeParamsWithHTTPClient creates a new CreateEpisodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEpisodeParamsWithHTTPClient(client *http.Client) *CreateEpisodeParams {
	return &CreateEpisodeParams{
		HTTPClient: client,
	}
}

/*
CreateEpisodeParams contains all the parameters to send to the API endpoint

	for the create episode operation.

	Typically these are written to a http.Request.
*/
type CreateEpisodeParams struct {

	/* ID.

	   Feed ID
	*/
	ID string

	/* Request.

	   CreateItems request
	*/
	Request *models.CreateEpisodeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create episode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEpisodeParams) WithDefaults() *CreateEpisodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create episode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEpisodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create episode params
func (o *CreateEpisodeParams) WithTimeout(timeout time.Duration) *CreateEpisodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create episode params
func (o *CreateEpisodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create episode params
func (o *CreateEpisodeParams) WithContext(ctx context.Context) *CreateEpisodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create episode params
func (o *CreateEpisodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create episode params
func (o *CreateEpisodeParams) WithHTTPClient(client *http.Client) *CreateEpisodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create episode params
func (o *CreateEpisodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create episode params
func (o *CreateEpisodeParams) WithID(id string) *CreateEpisodeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create episode params
func (o *CreateEpisodeParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the create episode params
func (o *CreateEpisodeParams) WithRequest(request *models.CreateEpisodeRequest) *CreateEpisodeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create episode params
func (o *CreateEpisodeParams) SetRequest(request *models.CreateEpisodeRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEpisodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
