// Code generated by go-swagger; DO NOT EDIT.

package episodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// CreateItemsReader is a Reader for the CreateItems structure.
type CreateItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateItemsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateItemsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateItemsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateItemsOK creates a CreateItemsOK with default headers values
func NewCreateItemsOK() *CreateItemsOK {
	return &CreateItemsOK{}
}

/*
CreateItemsOK describes a response with status code 200, with default header values.

OK
*/
type CreateItemsOK struct {
	Payload *models.CreateEpisodesResponse
}

// IsSuccess returns true when this create items o k response has a 2xx status code
func (o *CreateItemsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create items o k response has a 3xx status code
func (o *CreateItemsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create items o k response has a 4xx status code
func (o *CreateItemsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create items o k response has a 5xx status code
func (o *CreateItemsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create items o k response a status code equal to that given
func (o *CreateItemsOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateItemsOK) Error() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsOK  %+v", 200, o.Payload)
}

func (o *CreateItemsOK) String() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsOK  %+v", 200, o.Payload)
}

func (o *CreateItemsOK) GetPayload() *models.CreateEpisodesResponse {
	return o.Payload
}

func (o *CreateItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateEpisodesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemsBadRequest creates a CreateItemsBadRequest with default headers values
func NewCreateItemsBadRequest() *CreateItemsBadRequest {
	return &CreateItemsBadRequest{}
}

/*
CreateItemsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateItemsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create items bad request response has a 2xx status code
func (o *CreateItemsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create items bad request response has a 3xx status code
func (o *CreateItemsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create items bad request response has a 4xx status code
func (o *CreateItemsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create items bad request response has a 5xx status code
func (o *CreateItemsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create items bad request response a status code equal to that given
func (o *CreateItemsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateItemsBadRequest) Error() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateItemsBadRequest) String() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateItemsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateItemsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemsUnauthorized creates a CreateItemsUnauthorized with default headers values
func NewCreateItemsUnauthorized() *CreateItemsUnauthorized {
	return &CreateItemsUnauthorized{}
}

/*
CreateItemsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateItemsUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create items unauthorized response has a 2xx status code
func (o *CreateItemsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create items unauthorized response has a 3xx status code
func (o *CreateItemsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create items unauthorized response has a 4xx status code
func (o *CreateItemsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create items unauthorized response has a 5xx status code
func (o *CreateItemsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create items unauthorized response a status code equal to that given
func (o *CreateItemsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateItemsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateItemsUnauthorized) String() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateItemsUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateItemsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemsInternalServerError creates a CreateItemsInternalServerError with default headers values
func NewCreateItemsInternalServerError() *CreateItemsInternalServerError {
	return &CreateItemsInternalServerError{}
}

/*
CreateItemsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateItemsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create items internal server error response has a 2xx status code
func (o *CreateItemsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create items internal server error response has a 3xx status code
func (o *CreateItemsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create items internal server error response has a 4xx status code
func (o *CreateItemsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create items internal server error response has a 5xx status code
func (o *CreateItemsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create items internal server error response a status code equal to that given
func (o *CreateItemsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateItemsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateItemsInternalServerError) String() string {
	return fmt.Sprintf("[POST /episodes/create][%d] createItemsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateItemsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateItemsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
