// Code generated by go-swagger; DO NOT EDIT.

package episodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEpisodeParams creates a new GetEpisodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEpisodeParams() *GetEpisodeParams {
	return &GetEpisodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEpisodeParamsWithTimeout creates a new GetEpisodeParams object
// with the ability to set a timeout on a request.
func NewGetEpisodeParamsWithTimeout(timeout time.Duration) *GetEpisodeParams {
	return &GetEpisodeParams{
		timeout: timeout,
	}
}

// NewGetEpisodeParamsWithContext creates a new GetEpisodeParams object
// with the ability to set a context for a request.
func NewGetEpisodeParamsWithContext(ctx context.Context) *GetEpisodeParams {
	return &GetEpisodeParams{
		Context: ctx,
	}
}

// NewGetEpisodeParamsWithHTTPClient creates a new GetEpisodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEpisodeParamsWithHTTPClient(client *http.Client) *GetEpisodeParams {
	return &GetEpisodeParams{
		HTTPClient: client,
	}
}

/*
GetEpisodeParams contains all the parameters to send to the API endpoint

	for the get episode operation.

	Typically these are written to a http.Request.
*/
type GetEpisodeParams struct {

	/* ChannelID.

	   Feed ID
	*/
	ChannelID string

	/* ID.

	   Item ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get episode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEpisodeParams) WithDefaults() *GetEpisodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get episode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEpisodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get episode params
func (o *GetEpisodeParams) WithTimeout(timeout time.Duration) *GetEpisodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get episode params
func (o *GetEpisodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get episode params
func (o *GetEpisodeParams) WithContext(ctx context.Context) *GetEpisodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get episode params
func (o *GetEpisodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get episode params
func (o *GetEpisodeParams) WithHTTPClient(client *http.Client) *GetEpisodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get episode params
func (o *GetEpisodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the get episode params
func (o *GetEpisodeParams) WithChannelID(channelID string) *GetEpisodeParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the get episode params
func (o *GetEpisodeParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithID adds the id to the get episode params
func (o *GetEpisodeParams) WithID(id string) *GetEpisodeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get episode params
func (o *GetEpisodeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEpisodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channelId
	if err := r.SetPathParam("channelId", o.ChannelID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
