// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateEpisodeRequest create episode request
//
// swagger:model CreateEpisodeRequest
type CreateEpisodeRequest struct {

	// authors
	// Example: The Owl
	Authors string `json:"authors,omitempty"`

	// description
	// Example: Bored owls talk about whatever happens to be on their minds
	Description string `json:"description,omitempty"`

	// file id
	// Example: file_2K9BWVNuo3sG4yM322fbP3mB6ls
	FileID string `json:"file_id,omitempty"`

	// link
	// Example: https://example.com
	Link string `json:"link,omitempty"`

	// title
	// Example: Bored Owls Online Radio
	Title string `json:"title,omitempty"`
}

// Validate validates this create episode request
func (m *CreateEpisodeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create episode request based on context it is used
func (m *CreateEpisodeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateEpisodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateEpisodeRequest) UnmarshalBinary(b []byte) error {
	var res CreateEpisodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
