// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFeedsRequest get feeds request
//
// swagger:model GetFeedsRequest
type GetFeedsRequest struct {

	// ids
	Ids []string `json:"ids"`

	// user ids
	UserIds []string `json:"userIds"`
}

// Validate validates this get feeds request
func (m *GetFeedsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get feeds request based on context it is used
func (m *GetFeedsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetFeedsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFeedsRequest) UnmarshalBinary(b []byte) error {
	var res GetFeedsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
