// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetChannelsRequest get channels request
//
// swagger:model GetChannelsRequest
type GetChannelsRequest struct {

	// ids
	Ids []string `json:"ids"`

	// user ids
	UserIds []string `json:"userIds"`
}

// Validate validates this get channels request
func (m *GetChannelsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get channels request based on context it is used
func (m *GetChannelsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetChannelsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetChannelsRequest) UnmarshalBinary(b []byte) error {
	var res GetChannelsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
