// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetEpisodesRequest get episodes request
//
// swagger:model GetEpisodesRequest
type GetEpisodesRequest struct {

	// channel ids
	ChannelIds []string `json:"channel_ids"`

	// ids
	Ids []string `json:"ids"`

	// user ids
	UserIds []string `json:"userIds"`
}

// Validate validates this get episodes request
func (m *GetEpisodesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get episodes request based on context it is used
func (m *GetEpisodesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetEpisodesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetEpisodesRequest) UnmarshalBinary(b []byte) error {
	var res GetEpisodesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
