// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetItemsRequest get items request
//
// swagger:model GetItemsRequest
type GetItemsRequest struct {

	// feed ids
	FeedIds []string `json:"feed_ids"`

	// ids
	Ids []string `json:"ids"`

	// user ids
	UserIds []string `json:"userIds"`
}

// Validate validates this get items request
func (m *GetItemsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get items request based on context it is used
func (m *GetItemsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetItemsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetItemsRequest) UnmarshalBinary(b []byte) error {
	var res GetItemsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
