// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RssDescription rss description
//
// swagger:model rss.Description
type RssDescription struct {

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this rss description
func (m *RssDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rss description based on context it is used
func (m *RssDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RssDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RssDescription) UnmarshalBinary(b []byte) error {
	var res RssDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
