// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RssGUID rss Guid
//
// swagger:model rss.Guid
type RssGUID struct {

	// is perma link
	IsPermaLink bool `json:"isPermaLink,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this rss Guid
func (m *RssGUID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rss Guid based on context it is used
func (m *RssGUID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RssGUID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RssGUID) UnmarshalBinary(b []byte) error {
	var res RssGUID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
