basePath: /api
definitions:
  ChannelResponse:
    properties:
      authors:
        example: The Owl
        type: string
        x-order: "4"
      created_at:
        example: "2023-01-01T01:02:03.456Z"
        format: date-time
        type: string
        x-order: "6"
      description:
        example: Bored owls talk about whatever happens to be on their minds
        type: string
        x-order: "5"
      feed_url:
        type: string
        x-order: "1"
      id:
        example: ch_2K9BWVNuo3sG4yM322fbP3mB6ls
        type: string
        x-order: "0"
      link:
        example: https://example.com
        type: string
        x-order: "3"
      title:
        example: Bored Owls Online Radio
        type: string
        x-order: "2"
      updated_at:
        example: "2023-01-01T01:02:03.456Z"
        format: date-time
        type: string
        x-order: "7"
    type: object
  ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  title: Simple Podcast Server REST API
  version: "0.1"
paths:
  /channels/{id}:
    get:
      parameters:
      - description: Channel ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ChannelResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get channel by ID
      tags:
      - Channels
swagger: "2.0"
