// Code generated by go-swagger; DO NOT EDIT.

package episodes_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// CreateEpisodesReader is a Reader for the CreateItems structure.
type CreateEpisodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEpisodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateEpisodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateEpisodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateEpisodesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateEpisodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateEpisodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateEpisodesOK creates a CreateEpisodesOK with default headers values
func NewCreateEpisodesOK() *CreateEpisodesOK {
	return &CreateEpisodesOK{}
}

/*
CreateEpisodesOK describes a response with status code 200, with default header values.

OK
*/
type CreateEpisodesOK struct {
	Payload *models.IDResponse
}

// IsSuccess returns true when this create episodes o k response has a 2xx status code
func (o *CreateEpisodesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create episodes o k response has a 3xx status code
func (o *CreateEpisodesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create episodes o k response has a 4xx status code
func (o *CreateEpisodesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create episodes o k response has a 5xx status code
func (o *CreateEpisodesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create episodes o k response a status code equal to that given
func (o *CreateEpisodesOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateEpisodesOK) Error() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesOK  %+v", 200, o.Payload)
}

func (o *CreateEpisodesOK) String() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesOK  %+v", 200, o.Payload)
}

func (o *CreateEpisodesOK) GetPayload() *models.IDResponse {
	return o.Payload
}

func (o *CreateEpisodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEpisodesBadRequest creates a CreateEpisodesBadRequest with default headers values
func NewCreateEpisodesBadRequest() *CreateEpisodesBadRequest {
	return &CreateEpisodesBadRequest{}
}

/*
CreateEpisodesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateEpisodesBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create episodes bad request response has a 2xx status code
func (o *CreateEpisodesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create episodes bad request response has a 3xx status code
func (o *CreateEpisodesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create episodes bad request response has a 4xx status code
func (o *CreateEpisodesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create episodes bad request response has a 5xx status code
func (o *CreateEpisodesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create episodes bad request response a status code equal to that given
func (o *CreateEpisodesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateEpisodesBadRequest) Error() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesBadRequest  %+v", 400, o.Payload)
}

func (o *CreateEpisodesBadRequest) String() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesBadRequest  %+v", 400, o.Payload)
}

func (o *CreateEpisodesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateEpisodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEpisodesUnauthorized creates a CreateEpisodesUnauthorized with default headers values
func NewCreateEpisodesUnauthorized() *CreateEpisodesUnauthorized {
	return &CreateEpisodesUnauthorized{}
}

/*
CreateEpisodesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateEpisodesUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create episodes unauthorized response has a 2xx status code
func (o *CreateEpisodesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create episodes unauthorized response has a 3xx status code
func (o *CreateEpisodesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create episodes unauthorized response has a 4xx status code
func (o *CreateEpisodesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create episodes unauthorized response has a 5xx status code
func (o *CreateEpisodesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create episodes unauthorized response a status code equal to that given
func (o *CreateEpisodesUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateEpisodesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateEpisodesUnauthorized) String() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateEpisodesUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateEpisodesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEpisodesNotFound creates a CreateEpisodesNotFound with default headers values
func NewCreateEpisodesNotFound() *CreateEpisodesNotFound {
	return &CreateEpisodesNotFound{}
}

/*
CreateEpisodesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateEpisodesNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create episodes not found response has a 2xx status code
func (o *CreateEpisodesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create episodes not found response has a 3xx status code
func (o *CreateEpisodesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create episodes not found response has a 4xx status code
func (o *CreateEpisodesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create episodes not found response has a 5xx status code
func (o *CreateEpisodesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create episodes not found response a status code equal to that given
func (o *CreateEpisodesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateEpisodesNotFound) Error() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesNotFound  %+v", 404, o.Payload)
}

func (o *CreateEpisodesNotFound) String() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesNotFound  %+v", 404, o.Payload)
}

func (o *CreateEpisodesNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateEpisodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEpisodesInternalServerError creates a CreateEpisodesInternalServerError with default headers values
func NewCreateEpisodesInternalServerError() *CreateEpisodesInternalServerError {
	return &CreateEpisodesInternalServerError{}
}

/*
CreateEpisodesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateEpisodesInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create episodes internal server error response has a 2xx status code
func (o *CreateEpisodesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create episodes internal server error response has a 3xx status code
func (o *CreateEpisodesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create episodes internal server error response has a 4xx status code
func (o *CreateEpisodesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create episodes internal server error response has a 5xx status code
func (o *CreateEpisodesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create episodes internal server error response a status code equal to that given
func (o *CreateEpisodesInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateEpisodesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateEpisodesInternalServerError) String() string {
	return fmt.Sprintf("[POST /channels/{id}/episodes][%d] createEpisodesInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateEpisodesInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateEpisodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
