// Code generated by go-swagger; DO NOT EDIT.

package episodes_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new episodes page API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for episodes page API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateEpisodes(params *CreateEpisodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEpisodesOK, error)

	GetEpisodes(params *GetEpisodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEpisodesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateEpisodes creates a new episode
*/
func (a *Client) CreateEpisodes(params *CreateEpisodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateEpisodesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateEpisodesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateItems",
		Method:             "POST",
		PathPattern:        "/channels/{id}/episodes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateEpisodesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateEpisodesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateItems: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetEpisodes lists episoded of the given channel
*/
func (a *Client) GetEpisodes(params *GetEpisodesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEpisodesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEpisodesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetItems",
		Method:             "GET",
		PathPattern:        "/channels/{id}/episodes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetEpisodesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetEpisodesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetItems: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
