// Code generated by go-swagger; DO NOT EDIT.

package episodes_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEpisodesParams creates a new GetEpisodesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEpisodesParams() *GetEpisodesParams {
	return &GetEpisodesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEpisodesParamsWithTimeout creates a new GetEpisodesParams object
// with the ability to set a timeout on a request.
func NewGetEpisodesParamsWithTimeout(timeout time.Duration) *GetEpisodesParams {
	return &GetEpisodesParams{
		timeout: timeout,
	}
}

// NewGetEpisodesParamsWithContext creates a new GetEpisodesParams object
// with the ability to set a context for a request.
func NewGetEpisodesParamsWithContext(ctx context.Context) *GetEpisodesParams {
	return &GetEpisodesParams{
		Context: ctx,
	}
}

// NewGetEpisodesParamsWithHTTPClient creates a new GetEpisodesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEpisodesParamsWithHTTPClient(client *http.Client) *GetEpisodesParams {
	return &GetEpisodesParams{
		HTTPClient: client,
	}
}

/*
GetEpisodesParams contains all the parameters to send to the API endpoint

	for the get episodes operation.

	Typically these are written to a http.Request.
*/
type GetEpisodesParams struct {

	/* ID.

	   Feed ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get episodes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEpisodesParams) WithDefaults() *GetEpisodesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get episodes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEpisodesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get episodes params
func (o *GetEpisodesParams) WithTimeout(timeout time.Duration) *GetEpisodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get episodes params
func (o *GetEpisodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get episodes params
func (o *GetEpisodesParams) WithContext(ctx context.Context) *GetEpisodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get episodes params
func (o *GetEpisodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get episodes params
func (o *GetEpisodesParams) WithHTTPClient(client *http.Client) *GetEpisodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get episodes params
func (o *GetEpisodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get episodes params
func (o *GetEpisodesParams) WithID(id string) *GetEpisodesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get episodes params
func (o *GetEpisodesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEpisodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
