// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// NewCreateChannelParams creates a new CreateChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateChannelParams() *CreateChannelParams {
	return &CreateChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateChannelParamsWithTimeout creates a new CreateChannelParams object
// with the ability to set a timeout on a request.
func NewCreateChannelParamsWithTimeout(timeout time.Duration) *CreateChannelParams {
	return &CreateChannelParams{
		timeout: timeout,
	}
}

// NewCreateChannelParamsWithContext creates a new CreateChannelParams object
// with the ability to set a context for a request.
func NewCreateChannelParamsWithContext(ctx context.Context) *CreateChannelParams {
	return &CreateChannelParams{
		Context: ctx,
	}
}

// NewCreateChannelParamsWithHTTPClient creates a new CreateChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateChannelParamsWithHTTPClient(client *http.Client) *CreateChannelParams {
	return &CreateChannelParams{
		HTTPClient: client,
	}
}

/*
CreateChannelParams contains all the parameters to send to the API endpoint

	for the create channel operation.

	Typically these are written to a http.Request.
*/
type CreateChannelParams struct {

	/* Request.

	   CreateChannel request
	*/
	Request *models.CreateChannelRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChannelParams) WithDefaults() *CreateChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create channel params
func (o *CreateChannelParams) WithTimeout(timeout time.Duration) *CreateChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create channel params
func (o *CreateChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create channel params
func (o *CreateChannelParams) WithContext(ctx context.Context) *CreateChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create channel params
func (o *CreateChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create channel params
func (o *CreateChannelParams) WithHTTPClient(client *http.Client) *CreateChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create channel params
func (o *CreateChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create channel params
func (o *CreateChannelParams) WithRequest(request *models.CreateChannelRequest) *CreateChannelParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create channel params
func (o *CreateChannelParams) SetRequest(request *models.CreateChannelRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
