// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// NewCreateChannelsParams creates a new CreateChannelsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateChannelsParams() *CreateChannelsParams {
	return &CreateChannelsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateChannelsParamsWithTimeout creates a new CreateChannelsParams object
// with the ability to set a timeout on a request.
func NewCreateChannelsParamsWithTimeout(timeout time.Duration) *CreateChannelsParams {
	return &CreateChannelsParams{
		timeout: timeout,
	}
}

// NewCreateChannelsParamsWithContext creates a new CreateChannelsParams object
// with the ability to set a context for a request.
func NewCreateChannelsParamsWithContext(ctx context.Context) *CreateChannelsParams {
	return &CreateChannelsParams{
		Context: ctx,
	}
}

// NewCreateChannelsParamsWithHTTPClient creates a new CreateChannelsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateChannelsParamsWithHTTPClient(client *http.Client) *CreateChannelsParams {
	return &CreateChannelsParams{
		HTTPClient: client,
	}
}

/*
CreateChannelsParams contains all the parameters to send to the API endpoint

	for the create channels operation.

	Typically these are written to a http.Request.
*/
type CreateChannelsParams struct {

	/* Request.

	   CreateFeeds request
	*/
	Request *models.CreateChannelRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create channels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChannelsParams) WithDefaults() *CreateChannelsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create channels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChannelsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create channels params
func (o *CreateChannelsParams) WithTimeout(timeout time.Duration) *CreateChannelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create channels params
func (o *CreateChannelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create channels params
func (o *CreateChannelsParams) WithContext(ctx context.Context) *CreateChannelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create channels params
func (o *CreateChannelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create channels params
func (o *CreateChannelsParams) WithHTTPClient(client *http.Client) *CreateChannelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create channels params
func (o *CreateChannelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create channels params
func (o *CreateChannelsParams) WithRequest(request *models.CreateChannelRequest) *CreateChannelsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create channels params
func (o *CreateChannelsParams) SetRequest(request *models.CreateChannelRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateChannelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
