// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// CreateChannelsReader is a Reader for the CreateFeeds structure.
type CreateChannelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateChannelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateChannelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateChannelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateChannelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateChannelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateChannelsOK creates a CreateChannelsOK with default headers values
func NewCreateChannelsOK() *CreateChannelsOK {
	return &CreateChannelsOK{}
}

/*
CreateChannelsOK describes a response with status code 200, with default header values.

OK
*/
type CreateChannelsOK struct {
	Payload *models.IDResponse
}

// IsSuccess returns true when this create channels o k response has a 2xx status code
func (o *CreateChannelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create channels o k response has a 3xx status code
func (o *CreateChannelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create channels o k response has a 4xx status code
func (o *CreateChannelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create channels o k response has a 5xx status code
func (o *CreateChannelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create channels o k response a status code equal to that given
func (o *CreateChannelsOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateChannelsOK) Error() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsOK  %+v", 200, o.Payload)
}

func (o *CreateChannelsOK) String() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsOK  %+v", 200, o.Payload)
}

func (o *CreateChannelsOK) GetPayload() *models.IDResponse {
	return o.Payload
}

func (o *CreateChannelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateChannelsBadRequest creates a CreateChannelsBadRequest with default headers values
func NewCreateChannelsBadRequest() *CreateChannelsBadRequest {
	return &CreateChannelsBadRequest{}
}

/*
CreateChannelsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateChannelsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create channels bad request response has a 2xx status code
func (o *CreateChannelsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create channels bad request response has a 3xx status code
func (o *CreateChannelsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create channels bad request response has a 4xx status code
func (o *CreateChannelsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create channels bad request response has a 5xx status code
func (o *CreateChannelsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create channels bad request response a status code equal to that given
func (o *CreateChannelsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateChannelsBadRequest) Error() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateChannelsBadRequest) String() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateChannelsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateChannelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateChannelsUnauthorized creates a CreateChannelsUnauthorized with default headers values
func NewCreateChannelsUnauthorized() *CreateChannelsUnauthorized {
	return &CreateChannelsUnauthorized{}
}

/*
CreateChannelsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateChannelsUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create channels unauthorized response has a 2xx status code
func (o *CreateChannelsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create channels unauthorized response has a 3xx status code
func (o *CreateChannelsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create channels unauthorized response has a 4xx status code
func (o *CreateChannelsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create channels unauthorized response has a 5xx status code
func (o *CreateChannelsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create channels unauthorized response a status code equal to that given
func (o *CreateChannelsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateChannelsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateChannelsUnauthorized) String() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateChannelsUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateChannelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateChannelsInternalServerError creates a CreateChannelsInternalServerError with default headers values
func NewCreateChannelsInternalServerError() *CreateChannelsInternalServerError {
	return &CreateChannelsInternalServerError{}
}

/*
CreateChannelsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateChannelsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create channels internal server error response has a 2xx status code
func (o *CreateChannelsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create channels internal server error response has a 3xx status code
func (o *CreateChannelsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create channels internal server error response has a 4xx status code
func (o *CreateChannelsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create channels internal server error response has a 5xx status code
func (o *CreateChannelsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create channels internal server error response a status code equal to that given
func (o *CreateChannelsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateChannelsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateChannelsInternalServerError) String() string {
	return fmt.Sprintf("[POST /channels][%d] createChannelsInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateChannelsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateChannelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
