// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetChannelParams creates a new GetChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetChannelParams() *GetChannelParams {
	return &GetChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetChannelParamsWithTimeout creates a new GetChannelParams object
// with the ability to set a timeout on a request.
func NewGetChannelParamsWithTimeout(timeout time.Duration) *GetChannelParams {
	return &GetChannelParams{
		timeout: timeout,
	}
}

// NewGetChannelParamsWithContext creates a new GetChannelParams object
// with the ability to set a context for a request.
func NewGetChannelParamsWithContext(ctx context.Context) *GetChannelParams {
	return &GetChannelParams{
		Context: ctx,
	}
}

// NewGetChannelParamsWithHTTPClient creates a new GetChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetChannelParamsWithHTTPClient(client *http.Client) *GetChannelParams {
	return &GetChannelParams{
		HTTPClient: client,
	}
}

/*
GetChannelParams contains all the parameters to send to the API endpoint

	for the get channel operation.

	Typically these are written to a http.Request.
*/
type GetChannelParams struct {

	/* ID.

	   Channel ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChannelParams) WithDefaults() *GetChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get channel params
func (o *GetChannelParams) WithTimeout(timeout time.Duration) *GetChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get channel params
func (o *GetChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get channel params
func (o *GetChannelParams) WithContext(ctx context.Context) *GetChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get channel params
func (o *GetChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get channel params
func (o *GetChannelParams) WithHTTPClient(client *http.Client) *GetChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get channel params
func (o *GetChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get channel params
func (o *GetChannelParams) WithID(id string) *GetChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get channel params
func (o *GetChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
