// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mkuznets.com/go/sps/api/models"
)

// ListChannelsReader is a Reader for the GetFeeds structure.
type ListChannelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListChannelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListChannelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListChannelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListChannelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListChannelsOK creates a ListChannelsOK with default headers values
func NewListChannelsOK() *ListChannelsOK {
	return &ListChannelsOK{}
}

/*
ListChannelsOK describes a response with status code 200, with default header values.

OK
*/
type ListChannelsOK struct {
	Payload *models.IDResponse
}

// IsSuccess returns true when this list channels o k response has a 2xx status code
func (o *ListChannelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list channels o k response has a 3xx status code
func (o *ListChannelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list channels o k response has a 4xx status code
func (o *ListChannelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list channels o k response has a 5xx status code
func (o *ListChannelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list channels o k response a status code equal to that given
func (o *ListChannelsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListChannelsOK) Error() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsOK  %+v", 200, o.Payload)
}

func (o *ListChannelsOK) String() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsOK  %+v", 200, o.Payload)
}

func (o *ListChannelsOK) GetPayload() *models.IDResponse {
	return o.Payload
}

func (o *ListChannelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListChannelsUnauthorized creates a ListChannelsUnauthorized with default headers values
func NewListChannelsUnauthorized() *ListChannelsUnauthorized {
	return &ListChannelsUnauthorized{}
}

/*
ListChannelsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListChannelsUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list channels unauthorized response has a 2xx status code
func (o *ListChannelsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list channels unauthorized response has a 3xx status code
func (o *ListChannelsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list channels unauthorized response has a 4xx status code
func (o *ListChannelsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list channels unauthorized response has a 5xx status code
func (o *ListChannelsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list channels unauthorized response a status code equal to that given
func (o *ListChannelsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ListChannelsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsUnauthorized  %+v", 401, o.Payload)
}

func (o *ListChannelsUnauthorized) String() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsUnauthorized  %+v", 401, o.Payload)
}

func (o *ListChannelsUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListChannelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListChannelsInternalServerError creates a ListChannelsInternalServerError with default headers values
func NewListChannelsInternalServerError() *ListChannelsInternalServerError {
	return &ListChannelsInternalServerError{}
}

/*
ListChannelsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListChannelsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list channels internal server error response has a 2xx status code
func (o *ListChannelsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list channels internal server error response has a 3xx status code
func (o *ListChannelsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list channels internal server error response has a 4xx status code
func (o *ListChannelsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list channels internal server error response has a 5xx status code
func (o *ListChannelsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list channels internal server error response a status code equal to that given
func (o *ListChannelsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ListChannelsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListChannelsInternalServerError) String() string {
	return fmt.Sprintf("[GET /channels][%d] listChannelsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListChannelsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListChannelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
